#!/usr/bin/env bash

docker build  -t siemonster/app app/ && (
    docker rm -f app
    docker run -itd --name app \
        $ADDITIONAL_DOCKER_ARGS \
        --restart=always \
        -v /opt/containers:/opt/containers:ro \
        -v /opt/containers/app:/opt/containers/app \
        -v /var/log/containers/app:/var/log \
        siemonster/app
)